packages:
  - "apps/*"
  - "packages/*"
  - "infra/sandbox"
allowBuilds:
  '@scarf/scarf': false
  esbuild: true
  unrs-resolver: true
  argon2: true
  es5-ext: true
  msgpackr-extract: true
  sharp: false
