#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

echo "==> BramhaV2 dev bootstrap"

# 1. Check prerequisites
command -v node >/dev/null 2>&1 || { echo "ERROR: node not installed"; exit 1; }
command -v pnpm >/dev/null 2>&1 || { echo "ERROR: pnpm not installed. Run: npm i -g pnpm"; exit 1; }
command -v docker >/dev/null 2>&1 || { echo "ERROR: docker not installed"; exit 1; }
command -v openssl >/dev/null 2>&1 || { echo "ERROR: openssl not installed"; exit 1; }

# 2. Install dependencies
echo "==> Installing dependencies..."
cd "$ROOT" && pnpm install

# 3. Root .env (compose interpolation only)
if [ ! -f "$ROOT/.env" ]; then
  echo "==> Creating .env from .env.example..."
  cp "$ROOT/.env.example" "$ROOT/.env"
fi

# 4. apps/api/.env — generate real dev secrets on first run.
#    Each machine gets unique keys; never reuse these in production.
if [ ! -f "$ROOT/apps/api/.env" ]; then
  echo "==> Generating apps/api/.env with fresh dev secrets..."
  JWT_PRIV_PEM=$(mktemp) && JWT_PUB_PEM=$(mktemp)
  openssl genpkey -algorithm ed25519 -out "$JWT_PRIV_PEM" 2>/dev/null
  openssl pkey -in "$JWT_PRIV_PEM" -pubout -out "$JWT_PUB_PEM" 2>/dev/null
  cat > "$ROOT/apps/api/.env" <<EOF
# Generated by scripts/bootstrap.sh — dev only, do not use in production
DATABASE_URL=postgresql://bramha_app:dev_only_app_password@localhost:5432/bramha_dev
REDIS_URL=redis://:dev_only_redis_password@localhost:6379
S3_ENDPOINT=http://localhost:9000
S3_REGION=us-east-1
S3_ACCESS_KEY_ID=dev_only_minio_root
S3_SECRET_ACCESS_KEY=dev_only_minio_password
S3_BUCKET_STAGING=bramha-staging
S3_BUCKET_CLEAN=bramha-clean
S3_BUCKET_QUARANTINE=bramha-quarantine
S3_BUCKET_ARTIFACTS=bramha-artifacts
CLAMAV_HOST=localhost
CLAMAV_PORT=3310
OTEL_ENDPOINT=http://localhost:4318
NODE_ENV=development
PORT=4000
JWT_SECRET=$(openssl rand -hex 32)
MASTER_KEY=$(openssl rand -base64 32)
JWT_PRIVATE_KEY_BASE64=$(base64 -w0 "$JWT_PRIV_PEM")
JWT_PUBLIC_KEY_BASE64=$(base64 -w0 "$JWT_PUB_PEM")
ALLOWED_ORIGINS=http://localhost:3000
EOF
  rm -f "$JWT_PRIV_PEM" "$JWT_PUB_PEM"
fi

# 5. apps/web/.env.local
if [ ! -f "$ROOT/apps/web/.env.local" ]; then
  echo "==> Creating apps/web/.env.local..."
  echo "NEXT_PUBLIC_API_URL=http://localhost:4000" > "$ROOT/apps/web/.env.local"
fi

# 6. Validate root env
echo "==> Validating environment..."
pnpm exec tsx "$ROOT/scripts/check-env.ts"

# 7. Build workspace packages the apps import at runtime
echo "==> Building workspace packages..."
pnpm --filter @bramha/shared --filter @bramha/db --filter @bramha/event-bus \
     --filter @bramha/agents --filter @bramha/mcp-connectors build

# 8. Start compose stack
echo "==> Starting dev services..."
cd "$ROOT" && docker compose -f infra/docker/compose.dev.yml up -d --build

# 9. Wait for postgres to be healthy
echo "==> Waiting for Postgres..."
RETRIES=30; COUNT=0
until docker compose -f infra/docker/compose.dev.yml exec -T postgres pg_isready -U bramha_dev -d bramha_dev >/dev/null 2>&1; do
  sleep 2; COUNT=$((COUNT+1))
  [ $COUNT -ge $RETRIES ] && { echo "ERROR: Postgres did not become ready after 60s"; exit 1; }
done
echo "  Postgres ready."

# 10. Run migrations (idempotent — tracked in _migrations table)
echo "==> Running migrations..."
DATABASE_URL="postgresql://bramha_dev:dev_only_postgres_password@localhost:5432/bramha_dev" \
  pnpm --filter @bramha/db db:migrate

# 11. Seed fixtures (idempotent inserts)
echo "==> Seeding..."
DATABASE_URL="postgresql://bramha_dev:dev_only_postgres_password@localhost:5432/bramha_dev" \
  pnpm --filter @bramha/db db:seed || echo "WARN: seed failed (non-fatal for fresh setups)"

echo ""
echo "✓ Dev stack ready!"
echo "  API:            pnpm --filter @bramha/api build && pnpm --filter @bramha/api start:dev   (http://localhost:4000, docs at /docs)"
echo "  Web:            pnpm --filter @bramha/web dev                                            (http://localhost:3000)"
echo "  Agent runtime:  SYSTEM_USER_ID=00000000-0000-0000-0000-000000000099 REDIS_URL=redis://:dev_only_redis_password@localhost:6379 \\"
echo "                    DATABASE_URL=postgresql://bramha_app:dev_only_app_password@localhost:5432/bramha_dev \\"
echo "                    pnpm --filter @bramha/agent-runtime build && node apps/agent-runtime/dist/main.js"
echo "                  (00000000-0000-0000-0000-000000000099 is the reserved system_agent user — see 0026_system_agent.sql)"
echo "  Postgres:       postgresql://bramha_dev:dev_only_postgres_password@localhost:5432/bramha_dev"
echo "  Redis:          redis://:dev_only_redis_password@localhost:6379"
echo "  MinIO:          http://localhost:9000  (console: http://localhost:9001)"
echo "  ClamAV:         localhost:3310"
echo "  OTel:           http://localhost:4317 (gRPC), http://localhost:4318 (HTTP)"
